/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiQldRetailRouteImport } from './routes/api/qld/retail'
import { Route as ApiAbsCpiRouteImport } from './routes/api/abs/cpi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQldRetailRoute = ApiQldRetailRouteImport.update({
  id: '/api/qld/retail',
  path: '/api/qld/retail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAbsCpiRoute = ApiAbsCpiRouteImport.update({
  id: '/api/abs/cpi',
  path: '/api/abs/cpi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/abs/cpi': typeof ApiAbsCpiRoute
  '/api/qld/retail': typeof ApiQldRetailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/abs/cpi': typeof ApiAbsCpiRoute
  '/api/qld/retail': typeof ApiQldRetailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/abs/cpi': typeof ApiAbsCpiRoute
  '/api/qld/retail': typeof ApiQldRetailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/abs/cpi' | '/api/qld/retail'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/abs/cpi' | '/api/qld/retail'
  id: '__root__' | '/' | '/api/abs/cpi' | '/api/qld/retail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAbsCpiRoute: typeof ApiAbsCpiRoute
  ApiQldRetailRoute: typeof ApiQldRetailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qld/retail': {
      id: '/api/qld/retail'
      path: '/api/qld/retail'
      fullPath: '/api/qld/retail'
      preLoaderRoute: typeof ApiQldRetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/abs/cpi': {
      id: '/api/abs/cpi'
      path: '/api/abs/cpi'
      fullPath: '/api/abs/cpi'
      preLoaderRoute: typeof ApiAbsCpiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAbsCpiRoute: ApiAbsCpiRoute,
  ApiQldRetailRoute: ApiQldRetailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
